___

<a href='https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# NumPy 

NumPy (o Numpy) es una biblioteca de álgebra lineal para Python, la razón por la que es tan importante para la ciencia de datos con Python es que casi todas las bibliotecas del ecosistema PyData se basan en NumPy como uno de sus principales bloques de construcción.

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.
Solo aprenderemos los conceptos básicos de NumPy, ¡para comenzar necesitamos instalarlo!

## Instrucciones de instalación



**Se recomienda encarecidamente que instale Python utilizando la distribución de Anaconda para asegurarse de que todas las dependencias subyacentes (como las bibliotecas de Álgebra lineal) se sincronicen con el uso de una instalación de conda. Si tiene Anaconda, instale NumPy yendo a su terminal o símbolo del sistema y escribiendo:**
    
    conda install numpy
    
**Si no tiene Anaconda y no puede instalarlo, consulte la documentación oficial de Numpy en varias instrucciones de instalación. [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Una vez que haya instalado NumPy, puede importarlo como una biblioteca:

In [1]:
import numpy as np

Numpy tiene muchas funciones y capacidades integradas. No los cubriremos todos, sino que nos centraremos en algunos de los aspectos más importantes de Numpy: vectores, matrices, matrices y generación de números. Comencemos discutiendo las matrices.

# Numpy Arrays

Las matrices NumPy son la principal forma en que usaremos Numpy a lo largo del curso. Los arreglos Numpy vienen esencialmente en dos formas: vectores y matrices. Los vectores son matrices estrictamente 1-d y las matrices son 2-d (pero debe tener en cuenta que una matriz todavía puede tener solo una fila o una columna).

Comencemos nuestra introducción explorando cómo crear matrices NumPy.

## Creando NumPy Arrays

### Desde una Lista de Python

Podemos crear una matriz convirtiendo directamente una lista o lista de listas:

In [8]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

Hay muchas formas integradas de generar matrices.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generar matrices de ceros o unos

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Devuelve números espaciados uniformemente durante un intervalo especificado.

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Crea una matriz de identidad

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy también tiene muchas formas de crear matrices de números aleatorios:

### rand
Crea una matriz de la forma dada y la rellena con
muestras aleatorias de una distribución uniforme
entre``[0, 1)``.

In [21]:
np.random.rand(2)

array([0.53035289, 0.36918986])

In [22]:
np.random.rand(5,5)

array([[0.32155448, 0.35594011, 0.96548191, 0.51759887, 0.31722937],
       [0.36748872, 0.93693957, 0.91198887, 0.17673952, 0.17673395],
       [0.02777579, 0.87588724, 0.57842566, 0.30335518, 0.02492896],
       [0.92924539, 0.31898082, 0.92971461, 0.01259219, 0.86069854],
       [0.92674722, 0.48701974, 0.12196185, 0.22617826, 0.23567607]])

### randn

Devuelve una muestra (o muestras) de la distribución "normal estándar". A diferencia de rand, que es uniforme:

In [11]:
np.random.randn(2)

array([-1.370517  ,  0.44368468])

In [23]:
np.random.randn(5,5)

array([[ 1.20930998, -0.23444726, -1.0098463 ,  0.06576035,  1.12262737],
       [ 0.15197175, -1.07795271,  1.0318266 , -0.98656555,  0.39615182],
       [ 0.54662776,  0.89917848, -1.00215339, -0.10023782, -1.3709077 ],
       [-0.2215108 ,  0.87641483, -0.56311613,  0.48940558, -0.9141805 ],
       [ 0.67295046, -0.37401389, -2.89863945, -0.22582603, -1.44699294]])

### randint
Devuelve enteros aleatorios desde `low` (inclusive) hasta `high` (exclusivo).

In [27]:
np.random.randint(1,100)

81

In [28]:
np.random.randint(1,100,10)

array([74,  9, 91, 62, 78,  9, 96, 28, 88, 33])

## Array Attributes and Methods

Analicemos algunos atributos y métodos útiles o una matriz:

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([ 5, 48, 16, 40,  5, 12, 38, 33, 33, 29])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma.

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar sus ubicaciones de índice usando argmin o argmax

In [35]:
ranarr

array([ 5, 48, 16, 40,  5, 12, 38, 33, 33, 29])

In [36]:
ranarr.max()

48

In [37]:
ranarr.argmax()

1

In [38]:
ranarr.min()

5

In [39]:
ranarr.argmin()

0

## Shape

La forma es un atributo que tienen las matrices (no un método):

In [53]:
# Vector
arr.shape

(25,)

In [54]:
# Observe los dos conjuntos de corchetes
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [55]:
arr.reshape(1,25).shape

(1, 25)

In [65]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [60]:
arr.reshape(5,5).shape

(5, 5)

### dtype

También puedes conocer el tipo de datos del objeto en la matriz:

In [57]:
arr.dtype

dtype('int32')

# Buen trabajo!